
deploy:
    stage: Deploy
    script:
    - rm -f from/css-test/style-test-mobile.css
    - cp -f from/style-test-mobile.css from/css-test
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
    only:
    - master

helloworld:
    stage: Trigger-cross-projects
            trigger: helloworld
