# trigger_build:
#   stage: deploy
#   script:
#     - $curl = curl_init();
#     - "curl -X POST -F token=2bcceb8b8027b220206ef7e1132c41 -F ref=master https://gitlab.com/api/v4/projects/21167331/trigger/pipeline"
#   only:
#     - develop
