rspec:
  stage: test
  script: 
    - rm -f from/css-test/style-test-mobile.css
    - cp -f from/style-test-mobile.css from/css-test
staging:
  variables:
    ENVIRONMENT: staging
  stage: deploy
  trigger: ../helloworld